name = "redmine-summary"
main = "src/index.js"
compatibility_date = "2024-05-02"

[vars]
REDMINE_BASE = "http://your-redmine-url.com"
AI_ENDPOINT = "https://api.openai.com/v1/chat/completions"
API_KEY = "sk-"