name = "redmine-summary"
main = "src/index.js"
compatibility_date = "2024-05-02"

[vars]
REDMINE_BASE = "http://your-redmine-url.com"


AI_ENDPOINT = "https://some_ai_provider.com/chat/completions"
AI_API_KEY = "sk-"
AI_API_MODEL = "gpt-3.5-turbo"